# Generated by Django 4.2.7 on 2024-02-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=18, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
